"""add property sub_type

Revision ID: 109f675625e5
Revises: 45c06f438668
Create Date: 2026-05-04 13:22:07.551573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109f675625e5'
down_revision: Union[str, None] = '45c06f438668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('sub_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_properties_sub_type'), 'properties', ['sub_type'], unique=False)
    # ### end Alembic commands ###

    # Data migration
    connection = op.get_bind()
    # Studio -> Appartement / Studio
    connection.execute(sa.text("UPDATE properties SET sub_type = 'Studio', type = 'Appartement' WHERE type = 'Studio'"))
    # Local commercial -> Local / Local commercial
    connection.execute(sa.text("UPDATE properties SET sub_type = 'Local commercial', type = 'Local' WHERE type = 'Local commercial'"))
    # Bureau -> Local / Local bureautique
    connection.execute(sa.text("UPDATE properties SET sub_type = 'Local bureautique', type = 'Local' WHERE type = 'Bureau'"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_sub_type'), table_name='properties')
    op.drop_column('properties', 'sub_type')
    # ### end Alembic commands ###
