"""make_visit_date_timezone_aware

Revision ID: 9206469d1717
Revises: d114d752309d
Create Date: 2026-05-13 09:45:04.244589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9206469d1717'
down_revision: Union[str, None] = 'd114d752309d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'visit_date',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_requests_assigned_user_id'), 'requests', ['assigned_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_assigned_user_id'), table_name='requests')
    op.alter_column('requests', 'visit_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###
