"""replace_enums_with_strings

Revision ID: c4f463b2c748
Revises: 0001
Create Date: 2026-05-01 12:51:04.979609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f463b2c748'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'type',
               existing_type=postgresql.ENUM('Appartement', 'Villa', 'Studio', 'Local commercial', 'Terrain', 'Bureau', name='property_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('properties', 'status',
               existing_type=postgresql.ENUM('Disponible', 'Réservé', 'Vendu', 'Loué', name='property_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('properties', 'vocation',
               existing_type=postgresql.ENUM('Vente', 'Location', name='property_vocation_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('properties', 'validation',
               existing_type=postgresql.ENUM('Validée', 'En attente', 'Brouillon', name='property_validation_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('properties_reference_key', 'properties', type_='unique')
    op.drop_index('ix_properties_reference', table_name='properties')
    op.create_index(op.f('ix_properties_reference'), 'properties', ['reference'], unique=True)
    op.alter_column('users', 'zone',
               existing_type=postgresql.ENUM('Tunis', 'La Marsa', 'Carthage', 'Gammarth', 'Sidi Bou Saïd', 'La Goulette', 'Le Bardo', 'Ariana', 'Ben Arous', 'Manouba', name='zone_enum'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CHEF_AGENCE', 'AGENT', 'COORDINATEUR', name='user_role_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CHEF_AGENCE', 'AGENT', 'COORDINATEUR', name='user_role_enum'),
               existing_nullable=False)
    op.alter_column('users', 'zone',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Tunis', 'La Marsa', 'Carthage', 'Gammarth', 'Sidi Bou Saïd', 'La Goulette', 'Le Bardo', 'Ariana', 'Ben Arous', 'Manouba', name='zone_enum'),
               existing_nullable=True)
    op.drop_index(op.f('ix_properties_reference'), table_name='properties')
    op.create_index('ix_properties_reference', 'properties', ['reference'], unique=False)
    op.create_unique_constraint('properties_reference_key', 'properties', ['reference'])
    op.alter_column('properties', 'validation',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Validée', 'En attente', 'Brouillon', name='property_validation_enum'),
               existing_nullable=False)
    op.alter_column('properties', 'vocation',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Vente', 'Location', name='property_vocation_enum'),
               existing_nullable=False)
    op.alter_column('properties', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Disponible', 'Réservé', 'Vendu', 'Loué', name='property_status_enum'),
               existing_nullable=False)
    op.alter_column('properties', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Appartement', 'Villa', 'Studio', 'Local commercial', 'Terrain', 'Bureau', name='property_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
