"""add visit request fields

Revision ID: d114d752309d
Revises: b0456c1d3446
Create Date: 2026-05-12 16:26:49.272336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd114d752309d'
down_revision: Union[str, None] = 'b0456c1d3446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('assigned_user_id', sa.Uuid(), nullable=True))
    op.add_column('requests', sa.Column('visit_date', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('status', sa.String(length=32), server_default='pending', nullable=False))
    op.add_column('requests', sa.Column('source', sa.String(length=32), server_default='website', nullable=False))
    op.add_column('requests', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'requests', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'notes')
    op.drop_column('requests', 'source')
    op.drop_column('requests', 'status')
    op.drop_column('requests', 'visit_date')
    op.drop_column('requests', 'assigned_user_id')
    # ### end Alembic commands ###
